### ISSUE TITLE
Support Go 1.22

### ISSUE THREAD

**Issue by stefanb** [juicedata/juicefs#4339]
**What happened**:

Fails to build with Go 1.22 (scheduled for February, currently at rc1)
* https://github.com/Homebrew/homebrew-core/pull/157782

Error log: https://github.com/Homebrew/homebrew-core/actions/runs/7284497233/job/19850411474#step:3:11882
````
  # github.com/pyroscope-io/godeltaprof/internal/pprof
  /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/pyroscope-io/godeltaprof@v0.1.2/internal/pprof/delta_mutex.go:25:20: undefined: runtime_cyclesPerSecond
  /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/pyroscope-io/godeltaprof@v0.1.2/internal/pprof/proto.go:400:8: undefined: runtime_expandFinalInlineFrame
  make: *** [juicefs] Error 1
````

**What you expected to happen**:

Build same as with Go 1.21

**How to reproduce it (as minimally and precisely as possible)**:

1. Install Go 1.22 rc1
2. Try to build with `go1.22rc1 build ./...` 

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by stefanb** [comment]
Note that once this is fixed it would still need a tagged release so that it can easily be picked up by https://github.com/Homebrew/homebrew-core/pull/157782 and others.
