### ISSUE TITLE
Build fails with Go 1.23

### ISSUE THREAD

**Issue by stefanb** [juicedata/juicefs#5047]
**What happened**:

Build with Go 1.23 rc1 & rc2 fails.

**What you expected to happen**:

Build to succeed.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

Build error
````
  ...
  # github.com/grafana/pyroscope-go/godeltaprof/internal/pprof
  /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/grafana/pyroscope-go/godeltaprof@v0.1.6/internal/pprof/delta_mutex.go:30:20: undefined: runtime_cyclesPerSecond
  /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/grafana/pyroscope-go/godeltaprof@v0.1.6/internal/pprof/proto.go:320:8: undefined: runtime_expandFinalInlineFrame
  make: *** [juicefs] Error 1
````

Indicating the upstream problems
* https://github.com/grafana/pyroscope-go/issues/103
* https://github.com/golang/go/issues/67548

The upstream fixes still needs to be released.

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version: 1.2.0
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:
  * Build attempt https://github.com/Homebrew/homebrew-core/pull/175310
  * Formula: https://github.com/Homebrew/homebrew-core/blob/master/Formula/j/juicefs.rb
  * Go 1.23 no longer allows //go:linkname * runtime.* link instructioins, see
  * Go 1.23 release notes: https://tip.golang.org/doc/go1.23#linker
  * Proposal: https://github.com/golang/go/issues/67401

**Comment by zhijian-pro** [comment]
Thanks, we will fix our code after the upstream fixes

**Comment by stefanb** [comment]
FYI, upstream pyroscope-go has released a fix for Go 1.23:
https://github.com/grafana/pyroscope-go/releases/tag/godeltaprof%2Fv0.1.8
