### PR TITLE
Bump pyroscope client and godeltaprof to support Go 1.22

### LINKED ISSUE #4339: Support Go 1.22
**What happened**:

Fails to build with Go 1.22 (scheduled for February, currently at rc1)
* https://github.com/Homebrew/homebrew-core/pull/157782

Error log: https://github.com/Homebrew/homebrew-core/actions/runs/7284497233/job/19850411474#step:3:11882
````
  # github.com/pyroscope-io/godeltaprof/internal/pprof
  /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/pyroscope-io/godeltaprof@v0.1.2/internal/pprof/delta_mutex.go:25:20: undefined: runtime_cyclesPerSecond
  /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/pyroscope-io/godeltaprof@v0.1.2/internal/pprof/proto.go:400:8: undefined: runtime_expandFinalInlineFrame
  make: *** [juicefs] Error 1
````

**What you expected to happen**:

Build same as with Go 1.21

**How to reproduce it (as minimally and precisely as possible)**:

1. Install Go 1.22 rc1
2. Try to build with `go1.22rc1 build ./...` 

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

### PR DESCRIPTION
**Pull request by stefanb**
* `github.com/pyroscope-io/client` was moved to `github.com/grafana/pyroscope-go`, see redirect of https://github.com/pyroscope-io/client
* Go 1.22 support was added in `godeltaprof` 0.1.6 via https://github.com/grafana/pyroscope-go/pull/55
* Fixes #4339

### CODE REVIEW

File: cmd/main.go [hunk 1]
```diff
@@ -28,9 +28,9 @@ import (
 
 	"github.com/erikdubbelboer/gspt"
 	"github.com/google/uuid"
+	"github.com/grafana/pyroscope-go"
```
Comment (zhijian-pro) [inline cmd/main.go:31]: May need to add `	_ "github.com/grafana/pyroscope-go/godeltaprof/http/pprof"`

image

https://grafana.com/docs/pyroscope/latest/configure-client/grafana-agent/go_pull/

**Comment by stefanb** [comment]
Is it ok to to ditch ancient Go 1.18 and include 1.22rc1 in the build matrix, docs and go.mod?

From [build log](https://github.com/juicedata/juicefs/actions/runs/7521671582/job/20479733272?pr=4340#step:5:231):
````
# github.com/klauspost/compress/zstd
Error: ../../../go/pkg/mod/github.com/klauspost/compress@v1.17.3/zstd/dict.go:479:32: binary.LittleEndian.AppendUint32 undefined (type binary.littleEndian has no field or method AppendUint32)
Error: ../../../go/pkg/mod/github.com/klauspost/compress@v1.17.3/zstd/dict.go:490:32: binary.LittleEndian.AppendUint32 undefined (type binary.littleEndian has no field or method AppendUint32)
Error: ../../../go/pkg/mod/github.com/klauspost/compress@v1.17.3/zstd/dict.go:491:32: binary.LittleEndian.AppendUint32 undefined (type binary.littleEndian has no field or method AppendUint32)
Error: ../../../go/pkg/mod/github.com/klauspost/compress@v1.17.3/zstd/dict.go:492:32: binary.LittleEndian.AppendUint32 undefined (type binary.littleEndian has no field or method AppendUint32)
note: module requires Go 1.19
````

File: cmd/main.go (hunk 1 above)
Comment (stefanb) [reply cmd/main.go:31]: Done in 8bf5f5eab5e38f5777db4b6c990fd29d36d8f922.

Should it be added also in other places that import `_ "net/http/pprof"`?

Comment (zhijian-pro) [reply cmd/main.go:31]: `cmd/main.go` is the unified entry point for the juicefs program, so I don't think it needs to be added anywhere else.

File: go.mod [hunk 2]
```diff
@@ -1,6 +1,6 @@
 module github.com/juicedata/juicefs
 
-go 1.18
```
Comment (zhijian-pro) [inline go.mod:3]: I tested without upgrading and it's ok here.

Comment (stefanb) [reply go.mod:3]: Yeah, the version number here serves two purposes
* Other module users: Minimal required Go version number to build - from this perspective it requires upgrade
* Go compiler: Defines default behaviour in case it changes between versions - from this perspective upgrade is not required, but with enough test coverage it can be safely done in this case.

Comment (zhijian-pro) [reply go.mod:3]: If we wait for #4334 this pr to merge, we shouldn't have this problem anymore

Comment (stefanb) [reply go.mod:3]: Either one is merged first, it is a minor and easy conflict to resolve.

Comment (stefanb) [reply go.mod]: Reverted to 1.18 in 621e9ef80b311beb2d8bbadc72a9c0c790a450c9.

**Comment by zhijian-pro** [comment]
We are in the process of upgrading the go version to 1.20. This pr can wait a little bit.

**Comment by stefanb** [comment]
Tnx, will wait for #4334, then rebase again and resolve any conflicts.

**Comment by stefanb** [comment]
Rebased and resolved all conflicts with #4334 regarding minimal required go version.

File: .github/workflows/verify.yml [hunk 3]
```diff
@@ -44,7 +44,7 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        version: ['1.20', '1.21']
+        version: ['1.20', '1.21', '>=1.22.0-rc.1']
```
Comment (stefanb) [inline .github/workflows/verify.yml:47]: After #4334 this is the only reference to Go version in this PR.

We can fix it to this specific rc1:
```suggestion
        version: ['1.20', '1.21', '1.22.0-rc.1']
```
but it is probably better to have it flexible, testing with future release candidates until Go 1.22 is released and only then change it to the usual:
```suggestion
        version: ['1.20', '1.21', '1.22']
```

Comment (zhijian-pro) [reply .github/workflows/verify.yml:47]: If this semantics is supported `>=1.22.0-rc.1`, then it seems fine to me to write it this way

**Comment by zhijian-pro** [comment]
LGTM!

**Review by zhijian-pro — APPROVED** [review]
